"""Assemble personalized DM messages from pre-generated details."""

import csv
import re
import json
from pathlib import Path

INPUT_CSV = Path(__file__).resolve().parent.parent / "projects" / "influencer-lists" / "fairfax-food-influencers.csv"
OUTPUT_CSV = Path(__file__).resolve().parent.parent / "projects" / "influencer-lists" / "fairfax-food-influencers-with-dms.csv"

DM_TEMPLATE = """Hey {name} -- love {detail}

It'd be great to have you come to Banh Mi Ong Beo. It's a vietnamese sandwich shop my wife and I run to share the flavors we grew up with.

It's on the house, don't even want a video, just your honest feedback.

Are you free this week to stop by?"""

# All 275 personalized details generated by Claude
DETAILS = {
    0: "the DMV food photography", 1: "the plant-based journey", 2: "the NoVA food coverage",
    3: "the food truck grind", 4: "the creative triple threat", 5: "the mezze vibes",
    6: "the pho drive-thru concept", 7: "the DMV dining coverage", 8: "the DC restaurant advocacy",
    9: "the late night hibachi", 10: "the craft BBQ game", 11: "the crab cake dedication",
    12: "the chicken and waffles combo", 13: "the Virginia storytelling", 14: "the Maryland crab cake reps",
    15: "the neighborhood kitchen concept", 16: "the michelin star work", 17: "the NOVA food finds",
    18: "the Peruvian culture mission", 19: "the southern NOLA vibes", 20: "the colorful DC lifestyle",
    21: "the DMV coffee and wine spot", 22: "the Japanese brunch concept", 23: "the DMV food blog",
    24: "the DC and NYC picks", 25: "the DC catering hustle", 26: "the homemade street tacos",
    27: "the gogo music mission", 28: "the modern Italian twist", 29: "the live grill experience",
    30: "the veteran-owned doughnut shop", 31: "the Ballston social house", 32: "the award-winning BBQ",
    33: "the Peruvian cocktail menu", 34: "the Caribbean-Italian fusion idea", 35: "the sno cream concept",
    36: "the DMV breakfast spot", 37: "the bottle-driven wine patio", 38: "the AYCE seafood boils",
    39: "the Latin coffee bar concept", 40: "the Baltimore flavor drip", 41: "the authentic Puerto Rican takeout",
    42: "the Southern Caribbean menu", 43: "the multi-location bakery hustle", 44: "the Del Ray community newsletter",
    45: "the family-owned Tex-Mex", 46: "the boba and pho content", 47: "the chocolate restaurant concept",
    48: "the twin foodie adventures", 49: "the Korean fried chicken", 50: "the locally sourced menu",
    51: "the NoVA real estate grind", 52: "the GF and vegan crepes", 53: "the DC dining coverage",
    54: "the K Street social club",
    55: "the 66-acre DC vision", 56: "the allure friday sets", 57: "the carry out grind",
    58: "the korean steakhouse vibes", 59: "the top 50 thai status", 60: "the island vibes menu",
    61: "the reston local finds", 62: "the coastal happy hour", 63: "the 750+ deal hunt",
    64: "the one-flavor philosophy", 65: "the veteran brewery mission", 66: "the sandwich game",
    67: "the family peanut legacy", 68: "the unapologetic DMV energy", 69: "the wood-fired BBQ dedication",
    70: "the memory-counting mindset", 71: "the patio and live music combo", 72: "the homemade mexican seasoning",
    73: "the third culture kitchen concept", 74: "the lao and thai fusion", 75: "the scratch-made comfort food",
    76: "the handmade taiyaki concept", 77: "the fresh daily seafood", 78: "the donburi bowl craft",
    79: "the custom organic cakes", 80: "the happy hour hustle", 81: "the DMV good eats hunt",
    82: "the villa gio concept", 83: "the pastry and private chef range", 84: "the asian street food bar",
    85: "the speakeasy soul vibes", 86: "the halal DMV resource", 87: "the 4pm happy hour deal",
    88: "the fairfax pizza spot", 89: "the pay it forward cafe", 90: "the european coast inspiration",
    91: "the VA/DC local finds", 92: "the custom pop-up cakes", 93: "the bake-at-home shipping idea",
    94: "the authentic KBBQ spread", 95: "the farm foraged concept", 96: "the pre-order cookie hustle",
    97: "the 40-plus masters grind", 98: "the french pastry family roots", 99: "the ceremonial matcha ritual",
    100: "the traditional Lebanese spread", 101: "the rooftop sports bar status", 102: "the wind-powered chocolate journey",
    103: "the soul food lunch hustle", 104: "the authentic Brazilian brunch", 105: "the custom poke bowl build",
    106: "the chevy chase neighborhood feel", 107: "the kobe beef licensing flex", 108: "the distinct dessert catering",
    109: "the bites sips and trips life", 110: "the multicultural recipe travels", 111: "the france to brazil food lens",
    112: "the custom letter cake game", 113: "the rammy award casual fine dining", 114: "the sushi friends concept",
    115: "the tuscan roots since 1979", 116: "the newark neighborhood italian", 117: "the vegan korean flair",
    118: "the authentic afghan banquet", 119: "the born and bread DC sourdough", 120: "the DMV food travel collab life",
    121: "the durban foodie anime combo", 122: "the wine country local flavors", 123: "the food and fire chef life",
    124: "the 2025 champion DJ set",
    125: "the neapolitan pizza oven", 126: "the michelin range", 127: "the village eats",
    128: "the wine country kitchen", 129: "the silo vibes", 130: "the persian modernist menu",
    131: "the fresh bagel spread", 132: "the laotian noma spot", 133: "the halal biryani game",
    134: "the authentic thai mission", 135: "the happy hour setup", 136: "the woodfire pasta bar",
    137: "the local ingredient focus", 138: "the sterling lounge", 139: "the fresh pasta program",
    140: "the ny pizza meets local brews", 141: "the neighborhood bar energy", 142: "the old-world butcher counter",
    143: "the luxury homebuilds", 144: "the rome reference", 145: "the skybar comfort food",
    146: "the loudoun local guide", 147: "the southeast asia itinerary", 148: "the solo eats adventure",
    149: "the halal turkish menu", 150: "the globally inspired crepe menu", 151: "the dmv restaurant produce hustle",
    152: "the new orleans authenticity", 153: "the wine and food pairing", 154: "the seasonal southern menu",
    155: "the mclean lifestyle coverage", 156: "the anacostia art space", 157: "the korean mexican fusion",
    158: "the famous birria game", 159: "the gopchang ayce setup", 160: "the all-you-can-eat spread",
    161: "the dmv foodie adventures", 162: "the dc seafood legacy", 163: "the luxury event design",
    164: "the restaurant worker advocacy", 165: "the home mortgage guidance", 166: "the buffalo cup and char style",
    167: "the elevated private chef menus", 168: "the daily happy hour", 169: "the games and brews setup",
    170: "the special occasion catering", 171: "the falls church dining hub", 172: "the kitchen creations",
    173: "the pakistani fine dining concept", 174: "the 24/7 diner energy", 175: "the decadent ice cream lineup",
    176: "the private dining wins", 177: "the vibrant indian dishes", 178: "the weekend taco setup",
    179: "the dmv macaron and food finds", 180: "the resy restaurant lounge", 181: "the bourbon and cigar experience",
    182: "the brazilian tableside service", 183: "the breakfast sandwich game", 184: "the flamenco tapas nights",
    185: "the live comedy bookings", 186: "the authentic indian catering", 187: "the colorful indian menu",
    188: "the 23-year reston real estate run", 189: "the korean bites concept", 190: "the mediterranean shawarma program",
    191: "the everyday little joys content", 192: "the caribbean fair oaks spot", 193: "the bogo wings happy hour",
    194: "the steak and seafood atmosphere", 195: "the mid-atlantic seasonal menu", 196: "the express thai lunch game",
    197: "the kingstowne pollo spot", 198: "the fajita and margarita combo", 199: "the old town fairfax legacy",
    200: "the chu hungry concept", 201: "the pan dulce tradition", 202: "the plaka gyro dedication",
    203: "the nova food finds", 204: "the mediterranean brunch spread", 205: "the tokyo ramen training",
    206: "the crepe and cortado combo", 207: "the remote eating life", 208: "the boozy chocolate craft",
    209: "the italian sub lineup", 210: "the root to table approach", 211: "the traditional italian kitchen",
    212: "the all-day indian dining", 213: "the late night halal run", 214: "the nyc pizza in dc",
    215: "the bbq catering setup", 216: "the global indian techniques", 217: "the independent family kitchen",
    218: "the new york meets napoli pies", 219: "the beer and burger pairing", 220: "the thai crispy crepe concept",
    221: "the camera and noodle combo", 222: "the global food hall curation", 223: "the spanish tapas sourcing",
    224: "the lebanese washington post feature", 225: "the dc commercial food shots", 226: "the colombian street food pop",
    227: "the dog friendly beer garden", 228: "the streets wayz energy", 229: "the tysons food hall lineup",
    230: "the made to order wedding cakes", 231: "the nova real estate team", 232: "the authentic mexican menu",
    233: "the homemade pasta in dc", 234: "the 30 year family kitchen", 235: "the comfort indian concept",
    236: "the moco happy hour wins", 237: "the handcrafted breads daily", 238: "the family owned beer spot",
    239: "the vietnamese boba snack bar", 240: "the bilingual childrens books", 241: "the chelsea fc food crossover",
    242: "the falls church top producer grind", 243: "the indian chinese fusion menu", 244: "the corporate catering operation",
    245: "the gluten free ice cream craft", 246: "the persian dj pastry combo", 247: "the regenerative herbalism work",
    248: "the phone eats first motto", 249: "the keep it simple approach", 250: "the small batch sourdough craft",
    251: "the herndon fine dining vibe", 252: "the actor trainer transformation story", 253: "the electric palm happy hour",
    254: "the military relocation expertise", 255: "the hokkaido noodle import", 256: "the stress free real estate take",
    257: "the cordon bleu cocktail dinners", 258: "the blue iguana mystery", 259: "the three year best restaurant streak",
    260: "the downtown fairfax wine bar", 261: "the honest buyer seller advice", 262: "the accokeek wings spot",
    263: "the georgetown wellness oasis", 264: "the strong lobster roll opinions", 265: "the old town lebanese classics",
    266: "the matcha thai dessert twist", 267: "the mac and chicken attitude", 268: "the chef franklin italian craft",
    269: "the dmv festival food lineup", 270: "the nova hidden restaurant finds", 271: "the real pit bbq operation",
    272: "the scratch made ashburn kitchen", 273: "the james beard chef collab", 274: "the historic manassas bistro",
}


def get_first_name(full_name, username):
    if not full_name or full_name.strip() == "":
        return username
    cleaned = re.sub(r'[^\w\s|,\-]', '', full_name).strip()
    if not cleaned:
        return username
    parts = re.split(r'[|,\-]', cleaned)
    first_part = parts[0].strip()
    if not first_part:
        return username
    words = first_part.split()
    return words[0] if words else username


def main():
    influencers = []
    with open(INPUT_CSV, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            influencers.append(row)

    with open(OUTPUT_CSV, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "Username", "Full Name", "Follower Count", "Profile URL",
            "First Name", "Personalized Detail", "DM Message"
        ])

        for i, inf in enumerate(influencers):
            first_name = get_first_name(inf["Full Name"], inf["Username"])
            detail = DETAILS.get(i, "what you're doing")
            message = DM_TEMPLATE.format(name=first_name, detail=detail)

            writer.writerow([
                inf["Username"],
                inf["Full Name"],
                inf["Follower Count"],
                inf["Profile URL"],
                first_name,
                detail,
                message,
            ])

    print(f"Done! {len(influencers)} personalized DMs saved to {OUTPUT_CSV}")


if __name__ == "__main__":
    main()
